set(Lib_ClientUI_SOURCES
  ${RAN_SRC}/Lib_ClientUI/Interface/AcademyConftDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityItemList.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityItemListSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityItemWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityPageMain.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ActivityPageMainSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AdminMessageDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AttendanceBookWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AudioOption.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicAnimationBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicCarrat.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicChat.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicChatLeftBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicChatRightBody.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicChatRightBodyEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicComboBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicComboBoxRollOver.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicEscMenu.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicGameMenu.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicHWOptionWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicInfoView.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicLevelDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicLineBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicLineBoxButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicLineBoxEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicLineBoxSmart.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicMiniBarGauge.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicPotionTray.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicProgressBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicQuickPotionSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicQuickPotionSlotEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicQuickSkillSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicQuickSkillSlotEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicScrollBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicScrollBarEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicScrollThumb.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicScrollThumbFrame.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicScrollThumbFrameUpdate.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicSkillTray.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextBoxEtc.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextBoxEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextBoxSimple.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextButtonEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTextButtonImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTree.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTreeEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicTreeNode.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicVarTextBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BasicVarTextBoxItemLink.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BikeColorSelect.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BikeColorSelectSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BikeColorWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BlockProgramAlarm.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BonusTimeDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BonusTimeGauge.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BonusTimeType.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BusWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Calendar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CarColorSelectSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CarColorWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CdmRankingDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TournamentScoreDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TournamentBanner.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CdmRankingDisplaySlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ChangeScaleWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ChangeSchoolWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreateInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreateInfoClass.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreateInfoSchool.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreateInfoSex.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreatePage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreatePageSet.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreatePageStyle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterCreateRotate.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterInfoViewPageStats.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterInfoViewPageStatsMark.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterInfoViewPageStatsRender.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterInfoViewWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterWindowEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterWindowMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CharacterWindowUpdate.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ChatMacroWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ChatShowFlag.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubAnnounce.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubBattle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubBattleModalWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubMake.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubMember.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubUnion.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ClubWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CodexWindow/CodexPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CodexWindow/CodexPageMain.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CodexWindow/CodexPageMainSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CodexWindow/StudentCodexButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CodexWindow/StudentCodexWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CompetitionNotifyButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CompetitionNotifyButtonAlarm.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CompetitionWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ConftConfirm.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ConftDisplayMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ConftModalWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ConftModalWindowMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CountMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CrowTargetInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CrowTargetInfoNpc.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CrowTargetInfoPlayer.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/CWRankingDisplay/CWRankingDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/DamageDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/DamageDisplayMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/DayBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/DialogueWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/DialogueWindowRenewal.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/EquipmentLockEnableWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/EquipmentLockInputWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/EquipmentLockRecoverWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/EscMenuOpen.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ExtraNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FaceStyleCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FItemFactTimeDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ForgotPassChangePage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ForgotPassPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FriendWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FriendWindowBlockPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FriendWindowNormalPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/FunctionOption.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleAgainBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleAnimationBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleResultBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleResultEvenBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleResultOddBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GambleSelectBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GamePlayOption.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GamePlayOptionMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GameStats.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GameTextControl.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GameTimeConvertUI.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GarbageInventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GarbageInventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryPageWear.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryPageWearEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GatherGauge.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GenderChangeWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GlobalRankingWindow/GlobalRankingPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GlobalRankingWindow/GlobalRankingPageSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GlobalRankingWindow/GlobalRankingWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HairColorCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HairStyleCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HeadChatDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HeadChatDisplayMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HelpDataMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HelpWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/HelpWindowWeb.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WebLinkWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InBoxWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InfoBoxContents.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InnerInterface.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InnerInterfaceModalMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InnerInterfaceMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InnerInterfaceSimple.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryLockEnableWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryLockInputWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryLockRecoverWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUIBank.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUIInven.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUIWishList.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_ItemMix.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_ItemMixInven.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_Rebuild.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_RebuildInven.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_Trade.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_TradeInven.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_Trash.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/InventoryUI_TrashInven.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemBankPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemBankWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemColorSelectSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemColorWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemGarbage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemInfoToolTip.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallWindowMenu.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallWindowMenuButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallWindowMenuPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMallWindowMenuSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMixInventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMixInventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMixWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemMove.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileEnhanceWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileMenuWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileItemSheet.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileUiKit.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileCharPanel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileSettingsPanel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileBagPanel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileSkillPanel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileQuestPanel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileChatMacroBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileChatChannelBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobileMiniMap.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemPreviewWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemPreviewWindowRender.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemRebuild.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SeparateItem.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AutoPotWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BossDetailsWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BossListSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/BossViewerButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemRebuildOption.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSearchResultWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopIcon.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopIconMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopGiftWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopGiftPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopItemSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemShopWindowWeb.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSlotEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSlotEx_Renew.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSlotPrivateMarket.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemSlot_Renew.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemTransferInventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemTransferInventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ItemTransferWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/KeySettingWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/GMGenItemWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AuctionWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AuctionStorageWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LargeMapWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LargeMapWindowEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LoadingMapThread.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LoadingThread.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LobbyTitle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/LoginPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MapMoveDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MapRequireCheck.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MarketPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MarketWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MessageWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MiniMap.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MiniMapInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MiniPartySlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MiniPartyWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobDBWindowItem.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobPreviewWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MobPreviewWindowRender.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModalWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModernQuestInfoDone.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModernQuestInfoProg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModernQuestListDone.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModernQuestListProg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ModernQuestWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MultiModeButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/MultiModeButtonImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NameDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NameDisplayMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCDialoguePage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCItemExchangeSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCItemExchangeWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCMarketPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCPromotionPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCShopItemSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/NPCShopWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/OuterInterface.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/OuterInterfaceModalMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/OuterInterfaceMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/OuterInterfaceSimple.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PandoraBoxButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PandoraBoxItemSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PandoraBoxResultsItemSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PandoraBoxWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyBuffInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyBuffInfoUnit.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyDisplayBuffInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyDisplayBuffInfoUnit.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyModalWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyModalWindowMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySearch/PartyFinderIcon.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySearch/PartyFinderSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySearch/PartyFinderWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySearch/PartyRequestModalWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartySlotDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PartyWindowCheckBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PassKeyboard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetColorCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetQuickSkillSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetQuickSkillSlot2.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetRebirthDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillInfoDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillInfoDisplay2.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetSkillWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetskinMixImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetStatus.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetStyleCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PetWindowRender.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PKComboDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PKComboType.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PKRankNotification.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PKRankNotificationInfo.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/KillFeedSelectorWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/AntiBotWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PlayerRankingButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketMake.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketSellWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketWantAddWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketShow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketShowMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PrivateMarketWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductWindowList.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductWindowProduct.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductWindowType.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ProductWindowTypeBase.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PtoPWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagBattleNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagHoldIcon.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPClubDeathMatchPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagPageBattle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagPageHistory.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagRankingPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagRankingPageSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagRebirthDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagScore.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagTopRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPCaptureTheFlagTopRankingsSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsBattleNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsPageBattle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsPageHistory.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsRankingPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsRankingPageSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsRebirthDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsScore.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsTopRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPSchoolWarsTopRankingsSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyranny2CaptureNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyBattleNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyCaptureNotice.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyPageBattle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyPageHistory.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyPageHistoryBuff.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyRankingPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyRankingPageSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyRebirthDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyTopRankings.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyTopRankingsSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyTowerCapture.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/PVPTyrannyTowerProgress.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QBoxButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QBoxButtonIcon.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestAlarm.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestGiftView.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestHelper.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestionItemDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestionItemType.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestList.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestMain.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestStep.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/QuestWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RebirthDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RebirthWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RebirthWindowButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RebuildInventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RebuildInventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ReceiveNoteWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/RegisterPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SecPassCheckPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SecPassSetPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SecurityWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterChangeMail.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterChangePass.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterChangePin.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterInfoPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterList.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterListItem.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterResetPin.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectCharacterTopUp.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectChinaAreaPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectServerChannel.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectServerPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SelectServerPageTw.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SentWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ShopItemSearchWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ShotCutBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SimpleHP.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SimpleMessageMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillFunc.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillImage33.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillInforToolTip.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillLinkInfoToolTip.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillSlot.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillTimeDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillTimeUnit.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillTrayTab.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SkillWindowToTray.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SlotCountMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SMSSendWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StaticUIManager.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StorageChargeCard.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StorageLockEnableWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StorageLockInputWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StorageLockRecoverWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StoragePage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StorageWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StudentRecordButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/StudentRecordWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SubMasterSet.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SwapImage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SystemBuffTimeDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SystemMessageDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/SystemMessageWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TargetInfoDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TargetInfoDisplayNpc.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TargetInfoDisplayPlayer.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TaxiWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/ThaiCCafeMark.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TradeControlPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TradeInventoryPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TradeInventoryWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TradePage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/TradeWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIEditBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIEditBoxMan.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIItemInfoLoader.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UILeftTopGroup.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIModal.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIMultiEditBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIOuterWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UISkillInfoLoader.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UITextControl.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIWindowBody.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIWindowEx.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/UIWindowTitle.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/CheckBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/MessageBox.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/NpcActionable.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/RnButton.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/RnProgressBar.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/Util/TapSelector.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VehicleBoosterDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VehicleStatus.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VehicleWindow.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VehicleWindowRender.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VideoOption.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VideoOptionMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VNGainSysGauge.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VNGainSysInventory.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/VNGainSysPage.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WaitDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WaitServerDialogue.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WarningMsg.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WeaponDisplay.cpp
  ${RAN_SRC}/Lib_ClientUI/Interface/WriteNoteWindow.cpp
)
